# Generated by Django 4.1.7 on 2024-07-19 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheNews', '0002_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
